import { ClampedText } from "@/components/clampedText";

export default function ClampedTask() {
  return (
    <div className="w-70 h-45 overflow-hidden">
      <ClampedText>
        BIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG
      </ClampedText>
      <ClampedText>
        BIG ZALUPABIG ZALUPABIG ZALUPABIG ZAL UPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG
        ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG
        ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG
        ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPA
      </ClampedText>
    </div>
  );
}
