import { ClampedText } from "@/components/clampedText";

export default function ClampedTask() {
  return (
    <div className="w-10 h-10">
      <ClampedText>
        BIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG
        ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG
        ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG
        ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPABIG ZALUPA
      </ClampedText>
    </div>
  );
}
